Repository wecode-bootcamp-korea/fullstack1-1st-Rush-and-Lush-backend, pull requests merged in 2021-07, with the labels that each got.

#1 [최민기] prisma schema 모델링 작성 완료
  prisma/migrations/20210709091620_create_rush_and_lush/migration.sql
  prisma/migrations/20210709111903_shipping_order/migration.sql
  prisma/migrations/20210709113023_change_capital/migration.sql
  prisma/schema.prisma
Labels: Status: 수정 요청

#2 [김지현] 로그인 및 회원가입 API 구현 중
  .gitignore
  Users/Router/index.js
  Users/Router/usersRouter.js
  Users/controllers/index.js
  Users/controllers/usersController.js
  Users/middleware/verify_jwt.js
  Users/models/index.js
  Users/models/usersDao.js
  Users/services/index.js
  Users/services/usersService.js
  app.js
  package-lock.json
  package.json
Labels: Status: Accepted

#3 [김지현] 카테고리 API 구현 중
  Categories/controllers/categoryController.js
  Categories/controllers/index.js
  Categories/middleware/verify_jwt.js
  Categories/models/categoryDao.js
  Categories/models/index.js
  Categories/router/categoryRouter.js
  Categories/router/index.js
  Categories/services/categoryService.js
  Categories/services/index.js
  app.js
  package-lock.json
  prisma/migrations/20210711113725_create_rush_and_lush/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  server.js
Labels: Status: Accepted

#4 [최민기] list 페이지에서 사용할 product API 생성
  .gitignore
  app.js
  controllers/ProductsController.js
  controllers/index.js
  models/ProductDao.js
  models/index.js
  package-lock.json
  package.json
  routes/ProductRouter.js
  routes/index.js
  server.js
  services/ProductService.js
  services/index.js
Labels: Status: 리뷰 요청

#5 [김지현] Router, Controller, Service, Model 파일 경로 수정
  Categories/controllers/index.js
  Categories/models/index.js
  Categories/router/index.js
  Categories/services/index.js
  Users/Router/index.js
  Users/controllers/index.js
  Users/middleware/verify_jwt.js
  Users/models/index.js
  Users/services/index.js
  app.js
  controllers/categoryController.js
  controllers/index.js
  controllers/usersController.js
  middleware/verify_jwt.js
  models/categoryDao.js
  models/index.js
  models/usersDao.js
  package.json
  routes/categoryRouter.js
  routes/index.js
  routes/usersRouter.js
  services/categoryService.js
  services/index.js
  services/usersService.js
Labels: Status: 리뷰 요청

#6 [김지현] 로그인 및 회원가입 API 에러 코드 수정
  controllers/usersController.js
Labels: Status: Accepted

#8 [김지현] categories - menu_id 출력하는 로직 추가
  controllers/categoryController.js
  models/categoryDao.js
  package.json
  services/categoryService.js
Labels: Status: Accepted
